export const localStorageBasicData = Object.freeze({
  language: "en",
  isDarkMode: false,
  mainData: [
    {
      id: "todos",
      name_ar: "المهام",
      name_en: "Todos",
      color: "#FF9800",
      isEssential: true,
      order: 1,
      tasks: [
        {
          id: "bqai9MSbfr",
          name_en: "change",
          name_ar: "تغير",
          description: "faefaefaefef",
          priority_level: "high",
          status: "done",
          due_date: "2024-09-19T01:10",
        },
        {
          id: "uGxi1wIT6L",
          name_en: "testTask1",
          name_ar: "مهمة اختبار",
          description: "تفاصيل مهمة اختبار رقم واحد",
          priority_level: "medium",
          status: "in progress",
          due_date: "2024-09-20T12:45",
        },
        {
          id: "vHxk7JKL6D",
          name_en: "updateTask",
          name_ar: "تحديث المهمة",
          description: "يجب تحديث هذه المهمة في الموعد المحدد",
          priority_level: "low",
          status: "pending",
          due_date: "2024-09-22T14:30",
        },
        {
          id: "aMxk9FTL3S",
          name_en: "fixBug",
          name_ar: "إصلاح خلل",
          description: "إصلاح الخلل المتعلق بواجهة المستخدم",
          priority_level: "high",
          status: "in review",
          due_date: "2024-09-18T09:10",
        },
        {
          id: "wAxl2MSi0R",
          name_en: "designLandingPage",
          name_ar: "تصميم الصفحة الرئيسية",
          description: "تصميم صفحة هبوط جديدة للموقع",
          priority_level: "medium",
          status: "done",
          due_date: "2024-09-25T10:00",
        },
        {
          id: "xBxj9RTK5E",
          name_en: "taskEnhancement",
          name_ar: "تحسين المهمة",
          description: "تحسين الأداء في جزء معين من التطبيق",
          priority_level: "high",
          status: "in progress",
          due_date: "2024-09-23T16:00",
        },
        {
          id: "yDxk5FSb9C",
          name_en: "newFeature",
          name_ar: "ميزة جديدة",
          description: "إضافة ميزة جديدة للتطبيق",
          priority_level: "urgent",
          status: "done",
          due_date: "2024-09-28T11:30",
        },
        {
          id: "zKxi7JSg2B",
          name_en: "clientMeeting",
          name_ar: "اجتماع مع العميل",
          description: "التحضير لاجتماع مهم مع العميل",
          priority_level: "low",
          status: "pending",
          due_date: "2024-09-29T13:00",
        },

      ],
    },
    {
      id: "in_progress",
      name_ar: "جاري",
      name_en: "In Progress",
      color: "#2196F3",
      isEssential: true,
      order: 2,
      tasks: [       
        {
          id: "lLxj2FRu8N",
          name_en: "performanceReview",
          name_ar: "مراجعة الأداء",
          description: "إجراء مراجعة أداء شاملة للفريق",
          priority_level: "medium",
          status: "done",
          due_date: "2024-09-21T08:45",
        },
        {
          id: "mPxl6HRn4O",
          name_en: "deployRelease",
          name_ar: "نشر الإصدار",
          description: "نشر الإصدار الجديد من التطبيق في بيئة الإنتاج",
          priority_level: "urgent",
          status: "in progress",
          due_date: "2024-09-27T19:00",
        }],
    },
    {
      id: "in_review",
      name_ar: "في مرحلة المراجعة",
      name_en: "In Review",
      color: "#9C27B0",
      isEssential: true,
      order: 3,
      tasks: [],
    },
    {
      id: "done",
      name_ar: "إنتهي",
      name_en: "Done",
      color: "#4CAF50",
      isEssential: true,
      order: 4,
      tasks: [],
    },
  ],
});
