export const localStorageBasicData = Object.freeze({
  language: "en",
  isDarkMode: false,
  mainData: [
    {
      id: "todos",
      name_ar: "المهام",
      name_en: "Tasks",
      color: "#FF9800",
      isEssential: true,
      order: 1,
      tasks: [
        {
          id: "uGxi1wIT6L",
          name_en: "Draft Project Proposal",
          name_ar: "كتابة مقترح المشروع",
          description_en: "Outline the main goals and deliverables for the new client project.",
          description_ar: "قم بكتابة مخطط تفصيلي للأهداف والمخرجات الرئيسية لمشروع العميل الجديد.",
          priority_level: "medium",
          status: "todos",
          due_date: "2024-09-20T12:45",
        },
        {
          id: "vHxk7JKL6D",
          name_en: "Review Budget Plan",
          name_ar: "مراجعة خطة الميزانية",
          description_en: "Ensure all departments' budget allocations are aligned with company goals.",
          description_ar: "تأكد من أن مخصصات الميزانية لجميع الأقسام متوافقة مع أهداف الشركة.",
          priority_level: "low",
          status: "todos",
          due_date: "2024-09-22T14:30",
        },
        {
          id: "aMxk9FTL3S",
          name_en: "Fix Login Bug",
          name_ar: "إصلاح خلل تسجيل الدخول",
          description_en: "Users experience login failure when using Safari. Address the bug immediately.",
          description_ar: "يعاني المستخدمون من فشل في تسجيل الدخول عند استخدام سفاري. قم بإصلاح الخلل فوراً.",
          priority_level: "high",
          status: "todos",
          due_date: "2024-09-18T09:10",
        },
        {
          id: "wAxl2MSi0R",
          name_en: "Design New Homepage",
          name_ar: "تصميم الصفحة الرئيسية الجديدة",
          description_en: "Create a fresh design concept for the homepage to enhance user engagement.",
          description_ar: "صمم مفهومًا جديدًا للصفحة الرئيسية لتعزيز تفاعل المستخدمين.",
          priority_level: "medium",
          status: "todos",
          due_date: "2024-09-25T10:00",
        },
        {
          id: "xBxj9RTK5E",
          name_en: "Refactor Codebase",
          name_ar: "إعادة هيكلة قاعدة الشيفرة",
          description_en: "Optimize the existing code to improve performance and maintainability.",
          description_ar: "قم بتحسين الشيفرة الحالية لتعزيز الأداء وسهولة الصيانة.",
          priority_level: "high",
          status: "todos",
          due_date: "2024-09-23T16:00",
        },
        {
          id: "yDxk5FSb9C",
          name_en: "Develop New Feature",
          name_ar: "تطوير ميزة جديدة",
          description_en: "Implement the chat functionality for the mobile app as requested.",
          description_ar: "قم بتنفيذ ميزة الدردشة لتطبيق الهاتف المحمول حسب الطلب.",
          priority_level: "urgent",
          status: "todos",
          due_date: "2024-09-28T11:30",
        },
        {
          id: "zKxi7JSg2B",
          name_en: "Client Feedback Meeting",
          name_ar: "اجتماع ملاحظات العميل",
          description_en: "Schedule and conduct a feedback session with the client on the latest sprint.",
          description_ar: "قم بجدولة وعقد جلسة ملاحظات مع العميل حول السبرينت الأخير.",
          priority_level: "low",
          status: "todos",
          due_date: "2024-09-29T13:00",
        },
      ],
    },
    {
      id: "in_progress",
      name_ar: "قيد التنفيذ",
      name_en: "In Progress",
      color: "#2196F3",
      isEssential: true,
      order: 2,
      tasks: [       
        {
          id: "lLxj2FRu8N",
          name_en: "Employee Performance Review",
          name_ar: "مراجعة أداء الموظفين",
          description_en: "Evaluate the quarterly performance for the tech team.",
          description_ar: "قم بتقييم الأداء الربع سنوي لفريق التقنية.",
          priority_level: "medium",
          status: "in_progress",
          due_date: "2024-09-21T08:45",
        },
        {
          id: "mPxl6HRn4O",
          name_en: "Deploy Production Release",
          name_ar: "نشر الإصدار الإنتاجي",
          description_en: "Push the latest version to production servers after QA approval.",
          description_ar: "قم بنشر الإصدار الأخير على خوادم الإنتاج بعد موافقة فريق ضمان الجودة.",
          priority_level: "urgent",
          status: "in_progress",
          due_date: "2024-09-27T19:00",
        }],
    },
    {
      id: "in_review",
      name_ar: "قيد المراجعة",
      name_en: "In Review",
      color: "#9C27B0",
      isEssential: true,
      order: 3,
      tasks: [
        {
          id: "kejfieuwj",
          name_en: "Codebase Review",
          name_ar: "مراجعة الشيفرة البرمجية",
          description_en: "Conduct a thorough review of the refactored components.",
          description_ar: "قم بمراجعة شاملة للمكونات التي أعيدت هيكلتها.",
          priority_level: "medium",
          status: "in_review",
          due_date: "2024-09-21T08:45",
        },
      ],
    },
    {
      id: "done",
      name_ar: "منتهي",
      name_en: "Done",
      color: "#4CAF50",
      isEssential: true,
      order: 4,
      tasks: [
        {
          id: "bqai9MSbfr",
          name_en: "Update Privacy Policy",
          name_ar: "تحديث سياسة الخصوصية",
          description_en: "Revised the privacy policy to align with recent regulations.",
          description_ar: "تم تحديث سياسة الخصوصية لتتماشى مع اللوائح الجديدة.",
          priority_level: "high",
          status: "done",
          due_date: "2024-09-19T01:10",
        },
      ],
    },
  ]
  
});
